### ISSUE TITLE
Sometimes .set() for a binary switch returns None

### ISSUE THREAD

**Issue by 2Fake** [2Fake/devolo_home_control_api#48]
**Describe the bug**
After some time running the API and might somes reconnects in local case, a binary switch can not be switched. Tried to reproduce it, by shutting down WiFi while running, but this doesn't triggered the error.

**To Reproduce**
?

**Expected behavior**
Switch is working after a reconnect always

**Desktop (please complete the following information):**
Docker Home Assistant

**Additional context**

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 453, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 484, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 622, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/devolo_home_control/switch.py", line 119, in turn_on
    self._binary_switch_property.set(state=True)
  File "/usr/local/lib/python3.7/site-packages/devolo_home_control_api/properties/binary_switch_property.py", line 35, in set
    if response.get("result").get("status") == 1:
AttributeError: 'NoneType' object has no attribute 'get'`

**Comment by 2Fake** [comment]
fixed with v0.11.0
